### ISSUE TITLE
Error when routing

### ISSUE THREAD

**Issue by vincent-lg-ma** [aaclause/BrailleExtender#105]
This has come out of the blue, but I hadn't been using BrailleExtender on this machine for some time and I finally did... only to find my Braille routing keys didn't work anymore.  Horrified, I tried to uncheck options and see if it changed things, though it seemed to make them worse.  In the NVDA log, there's this error:

```
error executing script: <bound method script_braille_routeTo of <globalCommands.GlobalCommands object at 0x07CCA770>> with gesture 'routing'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "C:\Users\...\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\patches.py", line 86, in script_braille_routeTo
    speechMode = speech.speechMode
AttributeError: module 'speech' has no attribute 'speechMode'
```

I am unsure why I see this message now.  Routing did work and I definitely didn't update NVDA or BralileExtender in a long while.  I checked that I was running on the latest (stable) version of BrailleExtender.  Is that an API change that went unnoticed?

Again thank you for all your work,

**Comment by aaclause** [comment]
Hello, and my apologies for the delay.
This bug is normally fixed since May...
Indeed an API change, see <https://github.com/nvaccess/nvda/pull/12395>.
Please provide your NVDA version and Braille Extender version if still occurs.

**Comment by vincent-lg-ma** [comment]
NVDA version is 2021.2, which is the latest stable if I'm not mistaken.  BrailleExtenderEdition is version 21.09.23:cccb2ed, which is the same on stable and development (if I'm not mistaken). To be sure, the problem occurs each time I use the routing cursor while in the console (routing in other applications does work).  I have the option to move the cursor when routing in review mode, which (usually) is pretty handy.
Thanks!

**Comment by aaclause** [comment]
Thank so much for this precision!
Could you try the dev version or the build from #106 => https://github.com/aaclause/BrailleExtender/suites/3870085932/artifacts/96276866

**Comment by aaclause** [comment]
New build: https://github.com/aaclause/BrailleExtender/suites/3870771364/artifacts/96296492
From this build you need to re-enable the option. General section, then "Emulate horizontal arrow keys to move cursor in edit areas". I highly recommend an app profile for this option.
This feature can now be used in focus mode and can help in some apps such as PyCharm or IntelliJ.

**Comment by vincent-lg-ma** [comment]
I've tried it.  For some reason I was still on an old version though I always accept updates.  And I have to say, the new version is really great.  Using the routing keys in Braille in review mode was a bit random before.  It's fully stable now.  It allows to do the same in other applications (PyCharm might be more accessible for Braille users, that's a win) and using emacs or vim in WSL is so much more comfortable, since it's possible to just use the routing keys even in a different Braille window, which didn't work beforehand.  Plus, the new feature about indicating formatting (spelling errors and such) is really great.  So a big thank you, this is a new game-changer for Braille users.

**Comment by aaclause** [comment]
Thanks for this feedback! :)

I'm not very satisfied with the new strings added in #106. Do you have any suggestions to be more concise?

New strings:

- "Emulate &horizontal arrow keys to move cursor in edit areas (can help in Windows consoles, IntelliJ, PyCharm... It is better to activate this option on demand or an application profile)":  
  the label of this option in general settings
- "Toggle emulate horizontal arrow keys to move cursor in edit areas":  
  the description of the gesture to enable/disable this feature on the fly. (can be assigned in input gestures dialog)
- "Moving the cursor with arrow keys enabled" / "Moving the cursor with arrow keys disabled":  
  A flash message displayed when we use the previous gesture
